### ISSUE TITLE
Toggl API

### ISSUE THREAD

**Issue by drkapoor** [ixudra/toggl#12]
Hi 

I really need your help. I'm struggling with getting time entries on Toggl via API.

I am working on a Laravel based project and I need to import time entries from my Toggl account. I am not able to pull records via API for some reason. I have configured Ixudra/toggl library correctly as per the given instructions. 

![image](https://user-images.githubusercontent.com/50033861/62907838-0dd74a80-bd2a-11e9-82f5-fa327e206f93.png)

This class is working partially. Its dashboard() function is working however timeEntries() function is not working as per the expectation. It does not return any error and returning NULL on each request.

Please have a look into this and shed some light on this and let us know if this is a known issue and how should we resolve this?

Thanks, 
Deepak

**Comment by elimentz** [comment]
You should use the correct date format. As specified in the api documentation, the date should have ISO 8601 format. Try the following: 

```php
$entries = Toggl::timeEntries('2019-08-08T08:00:00+00:00', '2019-08-13T08:00:00+00:00');
```

Or probably a better way, if you're using carbon dates:

```php
Toggl::timeEntries($startDate->toIso8601String(), $end->toIso8601String());
```

I should probably change that since carbon and/or string would be easier to work with. Something for the future :-)

**Comment by drkapoor** [comment]
Awesome, It resolves this issue, Thanks for the prompt reply. :)
